---
title: "Geocoding power stations"
format: html
---

## Purpose

Geocoding the power stations

```{r}
library(tidyverse)
```

### Column names

```{r}
names <- tibble::tibble(
               column = c(1L,2L,3L,4L,5L,6L,
                          7L,8L,9L,10L,11L,12L,13L,14L,15L,16L,17L,18L,
                          19L,20L,21L),
        swedish_title = c("Nummer",
                          "Företagets namn","Kommun, stad","Kraftstationenes namn eller läge",
                          "Drivkraft","Utbyggd fallhöjd i m",
                          "Installerad generatoreffekt i kVA","Strömart","Periodtal",
                          "Spänningssysstem volt","Huvudtransformatorns effeckt kVA",
                          "Ortstransformatorernas antal",
                          "Ortstransformatorernas sammanlagda effekt kVA",
                          "Anslutning år 1922 motorer kW","belysning kW","övriga apparater kW",
                          "summa kW","Energiförbrukning år 1922 kWh",
                          "Elektriferad åkerareal den 1/1 1923 hektar","Anmärkningar","Nummer"),
        english_title = c("Number",
                          "The name of the company","Municipality, city",
                          "The name or mode of power station","Driving force",
                          "Expanded fall height in m","Installed generator power in KVA",
                          "Streaming","Period number","Voltage voltage",
                          "The effect of the main transformer",
                          "The number of local transformers","The total effect of the local transformers",
                          "Connection in 1922 engines KW","Lighting kw",
                          "Other appliances kW","Sum kw",
                          "Energy consumption in 1922 kWh","Electrified arable land on 1/1 1923 hectares",
                          "Notes","Number")
   )

```

### Geocoding

```{r}
df_gotland <- readxl::read_excel("data/Gotland_power_stations.xlsx") %>% 
  janitor::clean_names()

df_gotland <- df_gotland %>% 
  mutate(location_to_code = str_squish(str_remove(kraftstationenes_namn_eller_lage, " .*")),
         location_to_code = str_c(location_to_code, ", Gotland, Sweden"))
```

```{r}
library(tidygeocoder)

locations <- geocode(df_gotland, address = location_to_code)

locations %>% 
  filter(is.na(lat)) %>% 
  select(location_to_code)
```


Vallviks cementfabrik is at Valleviken when you look on the map.

```{r}

```

